from __future__ import annotations

import html
import json
import re
from typing import Any, Dict, Iterable, Mapping

from repliq.ui_foundation import render_repliq_shell, ui_known_labels

CX2_MIGRATION_VERSION = "cx2.0"

# Exact UI-copy translations used by the owner-page compatibility adapter.
# Business/user content is not translated; only known product UI phrases are touched.
_CX2_EXACT: Dict[str, Dict[str, str]] = {
    "lv": {
        "Load": "Ielādēt",
        "Refresh": "Atjaunot",
        "Workspace": "Darba vide",
        "Setup": "Iestatīšana",
        "Logout": "Izrakstīties",
        "Open": "Atvērt",
        "Reset": "Atiestatīt",
        "Status": "Statuss",
        "Ready": "Gatavs",
        "Save": "Saglabāt",
        "Cancel": "Atcelt",
        "Clear": "Notīrīt",
        "Business profile": "Uzņēmuma profils",
        "Owner-safe workspace settings. Only non-secret business profile fields can be edited here.": "Droši uzņēmuma iestatījumi īpašniekam. Šeit var rediģēt tikai laukus, kas nesatur slepenu informāciju.",
        "Profile settings": "Profila iestatījumi",
        "Business name": "Uzņēmuma nosaukums",
        "Language": "Uzņēmuma valoda",
        "Timezone": "Laika josla",
        "Working hours": "Darba laiks",
        "Save profile": "Saglabāt profilu",
        "Raw profile readiness": "Profila tehniskais statuss",
        "Services": "Pakalpojumi",
        "Owner-safe service catalog. Edit services without opening admin configuration screens.": "Drošs pakalpojumu katalogs īpašniekam. Rediģējiet pakalpojumus bez administratora iestatījumu atvēršanas.",
        "Service setup": "Pakalpojumu iestatīšana",
        "Add example service": "Pievienot piemēra pakalpojumu",
        "Save services": "Saglabāt pakalpojumus",
        "Services JSON": "Pakalpojumu dati",
        "Raw readiness": "Tehniskais statuss",
        "Business Memory / FAQ": "Uzņēmuma zināšanas / BUJ",
        "Owner-safe receptionist facts: FAQ, policies, prices, address, and booking rules used in customer conversations.": "Drošas AI administratora zināšanas: BUJ, noteikumi, cenas, adrese un rezervēšanas kārtība klientu sarunām.",
        "Memory setup": "Zināšanu iestatīšana",
        "Add examples": "Pievienot piemērus",
        "Save memory / FAQ": "Saglabāt zināšanas / BUJ",
        "Latvian": "Latviešu",
        "Russian": "Krievu",
        "English": "Angļu",
        "Business memory LV": "Uzņēmuma zināšanas LV",
        "FAQ LV": "BUJ LV",
        "Booking rules LV": "Rezervēšanas noteikumi LV",
        "Business memory RU": "Uzņēmuma zināšanas RU",
        "FAQ RU": "BUJ RU",
        "Booking rules RU": "Rezervēšanas noteikumi RU",
        "Business memory EN": "Uzņēmuma zināšanas EN",
        "FAQ EN": "BUJ EN",
        "Booking rules EN": "Rezervēšanas noteikumi EN",
        "Generic optional fields": "Papildu izvēles lauki",
        "Business memory": "Uzņēmuma zināšanas",
        "FAQ": "BUJ",
        "Policies": "Noteikumi",
        "Booking rules": "Rezervēšanas noteikumi",
        "Price consistency": "Cenu saskaņotība",
        "Service catalog is the source of truth for prices. Business Memory should explain rules and exceptions, not duplicate conflicting price lists.": "Pakalpojumu katalogs ir galvenais cenu avots. Uzņēmuma zināšanām jāizskaidro noteikumi un izņēmumi, nevis jādublē pretrunīgi cenu saraksti.",
        "Edit services": "Rediģēt pakalpojumus",
        "Edit memory": "Rediģēt zināšanas",
        "Raw consistency payload": "Saskaņotības tehniskā informācija",
        "Calendar / availability": "Kalendārs / pieejamība",
        "Owner-safe calendar status and availability settings. Google OAuth/admin setup links stay hidden from owners.": "Drošs kalendāra statuss un pieejamības iestatījumi īpašniekam. Google OAuth un administratora saites netiek rādītas.",
        "Calendar status": "Kalendāra statuss",
        "Availability": "Pieejamība",
        "Save availability": "Saglabāt pieejamību",
        "Next actions": "Nākamās darbības",
        "Raw calendar readiness": "Kalendāra tehniskais statuss",
        "Telegram channel": "Telegram kanāls",
        "Owner-safe Telegram status. Bot tokens, webhook secrets and admin setup links are hidden from owners.": "Drošs Telegram statuss īpašniekam. Bota tokeni, webhook noslēpumi un administratora saites netiek rādīti.",
        "Webhook": "Webhook",
        "Usage": "Lietojums",
        "Raw Telegram readiness": "Telegram tehniskais statuss",
        "Final launch checklist": "Gala palaišanas pārbaude",
        "Owner-safe review of business profile, services, FAQ, price consistency, calendar, Telegram, billing and public launch readiness. Admin setup links and secrets are hidden.": "Drošs uzņēmuma profila, pakalpojumu, BUJ, cenu, kalendāra, Telegram, norēķinu un palaišanas gatavības pārskats. Administratora saites un noslēpumi netiek rādīti.",
        "Dashboard": "Pārskats",
        "Review items": "Pārbaudes punkti",
        "Raw launch checklist": "Palaišanas pārbaudes tehniskā informācija",
        "Client preview": "Klienta priekšskatījums",
        "Owner-safe dry-run preview. It uses services and Business Memory, but does not create calendar events, persist conversations, or send Telegram/SMS/WhatsApp messages.": "Drošs testa priekšskatījums. Tas izmanto pakalpojumus un uzņēmuma zināšanas, bet neveido kalendāra notikumus, nesaglabā sarunas un nesūta Telegram/SMS/WhatsApp ziņas.",
        "Launch checklist": "Palaišanas pārbaude",
        "Preview chat": "Priekšskatījuma saruna",
        "Preview reply": "Priekšskatījuma atbilde",
        "Catalog preview": "Kataloga priekšskatījums",
        "Raw preview payload": "Priekšskatījuma tehniskā informācija",
        "Conversation insights": "Sarunu analītika",
        "Owner-safe read-only visibility for live interactions. Preview messages from demo mode are shown as not persisted by design.": "Droša tikai lasāma reālo sarunu analītika. Demo režīma ziņas pēc noklusējuma netiek saglabātas.",
        "What customers ask": "Ko jautā klienti",
        "Service interest": "Interese par pakalpojumiem",
        "Price questions": "Jautājumi par cenām",
        "Answer source visibility": "Atbilžu avoti",
        "Channel status": "Kanālu statuss",
        "Recent interactions": "Jaunākās sarunas",
        "Raw owner-safe payload": "Droša tehniskā informācija",
        "Lead follow-up visibility": "Potenciālo klientu pārraudzība",
        "Owner-safe read-only queue for conversations that may need manual review. Stage 90 does not send notifications or customer messages.": "Droša tikai lasāma rinda sarunām, kurām var būt nepieciešama manuāla pārbaude. Šī sadaļa nesūta paziņojumus vai klientu ziņas.",
        "Insights": "Analītika",
        "Follow-up candidates": "Sarunas turpmākai saziņai",
        "Priority / reasons": "Prioritāte / iemesli",
        "Channel visibility": "Kanālu pārskats",
        "Conversation states": "Sarunu stāvokļi",
        "Recently resolved": "Nesen atrisināts",
        "Owner-safe account, workspace profile and billing summary. Read-only: no payment-provider calls and no account writes.": "Drošs konta, darba vides profila un norēķinu pārskats. Tikai lasāms: netiek veikti maksājumu pieprasījumi vai konta izmaiņas.",
        "Billing": "Norēķini",
        "Billing summary": "Norēķinu pārskats",
        "Workspace profile": "Darba vides profils",
        "Limitations": "Ierobežojumi",
        "Raw account payload": "Konta tehniskā informācija",
        "Setup health": "Iestatījumu statuss",
        "Owner-safe read-only tenant data quality guard. It highlights missing setup data without changing live runtime behavior.": "Droša tikai lasāma datu kvalitātes pārbaude. Tā parāda trūkstošos iestatījumus, nemainot sistēmas darbību.",
        "Launch review": "Palaišanas pārbaude",
        "Account": "Konts",
        "Components": "Komponenti",
        "Warnings": "Brīdinājumi",
        "Raw setup health payload": "Iestatījumu tehniskā informācija",
        "Read-only launch checkpoint": "Tikai lasāms palaišanas kontrolpunkts",
        "SMB launch smoke": "SMB palaišanas tests",
        "This page combines setup health, final launch review and safe client preview evidence. It never runs live dialogue, creates Calendar events or sends customer messages automatically.": "Šī lapa apvieno iestatījumu statusu, gala pārbaudi un droša klienta priekšskatījuma pierādījumus. Tā automātiski nepalaiž reālas sarunas, neveido kalendāra notikumus un nesūta klientu ziņas.",
        "Launch gates": "Palaišanas pārbaudes",
        "Manual smoke checklist": "Manuālā testa saraksts",
        "The controlled live booking/reschedule/cancel step is intentionally manual and may mutate the selected test calendar. This page does not run it.": "Kontrolētais reālais rezervēšanas, pārcelšanas un atcelšanas tests ir apzināti manuāls un var mainīt izvēlēto testa kalendāru. Šī lapa to nepalaiž.",
        "Owner-safe payload": "Droša tehniskā informācija",
        "Technical core lock": "Tehniskā kodola fiksācija",
        "Mature SMB readiness": "Mature SMB gatavība",
        "This page locks the current technical SMB product baseline. It deliberately does not claim that multilingual client navigation or the public visual website is finished; those are the next separate polish phase.": "Šī lapa fiksē pašreizējo SMB produkta tehnisko bāzi. Tā neapgalvo, ka daudzvalodu klienta navigācija vai publiskā vietne jau ir pabeigta; tas ir atsevišķs nākamais posms.",
        "Launch smoke": "Palaišanas tests",
        "Technical lock status": "Tehniskās gatavības statuss",
        "Readiness gates": "Gatavības pārbaudes",
        "Next phase: client experience polish": "Nākamais posms: klienta pieredzes uzlabošana",
        "Owner Billing": "Īpašnieka norēķini",
        "Owner-visible read-only subscription status.": "Īpašniekam redzams tikai lasāms abonementa statuss.",
        "Owner dashboard": "Īpašnieka pārskats",
        "Account center": "Konta centrs",
        "Owner control center": "Īpašnieka vadības centrs",
        "Owner session": "Īpašnieka sesija",
        "Subscription settings": "Abonementa iestatījumi",
        "Plan": "Plāns",
        "Subscription status": "Abonementa statuss",
        "Dialogs per month override": "Dialogu limits mēnesī",
        "Trial end ISO": "Izmēģinājuma beigas",
        "Billing provider": "Maksājumu pakalpojuma sniedzējs",
        "Current period end ISO": "Pašreizējā perioda beigas",
        "Customer id": "Klienta ID",
        "Subscription id": "Abonementa ID",
        "Reset dialogs override": "Atiestatīt dialogu limitu",
        "Billing notes": "Norēķinu piezīmes",
        "Save billing": "Saglabāt norēķinus",
        "Raw": "Tehniskā informācija",
        "No data in selected window.": "Izvēlētajā periodā nav datu.",
        "No interactions in selected window.": "Izvēlētajā periodā nav sarunu.",
        "No customer questions detected in selected window.": "Izvēlētajā periodā klientu jautājumi nav atrasti.",
        "No price questions detected in selected window.": "Izvēlētajā periodā cenu jautājumi nav atrasti.",
        "No service interest detected.": "Interese par pakalpojumiem nav atrasta.",
        "No answer source metadata.": "Nav datu par atbilžu avotiem.",
        "No channel activity.": "Kanālos nav aktivitātes.",
        "No next actions": "Nav nākamo darbību",
        "No next actions.": "Nav nākamo darbību.",
        "No required actions.": "Nav obligātu darbību.",
        "No components returned.": "Komponenti netika atrasti.",
        "No warnings returned.": "Brīdinājumu nav.",
        "No gates returned.": "Pārbaudes netika atrastas.",
        "No checklist returned.": "Pārbaudes saraksts netika atrasts.",
        "Owner login required": "Nepieciešama īpašnieka pieslēgšanās",
        "Load failed": "Ielāde neizdevās",
        "Save failed": "Saglabāšana neizdevās",
        "Saving…": "Saglabā…",
        "Unknown service": "Nezināms pakalpojums",
        "Source of truth": "Galvenais avots",
        "support controlled": "kopā ar atbalstu",
        "optional attention": "ieteicama pārbaude",
        "Target languages": "Mērķa valodas",
        "This is intentionally not marked complete by Stage 95.": "Stage 95 apzināti neatzīmē šo posmu kā pabeigtu.",
    },
    "ru": {
        "Load": "Загрузить",
        "Refresh": "Обновить",
        "Workspace": "Рабочая область",
        "Setup": "Настройка",
        "Logout": "Выйти",
        "Open": "Открыть",
        "Reset": "Сбросить",
        "Status": "Статус",
        "Ready": "Готово",
        "Save": "Сохранить",
        "Cancel": "Отмена",
        "Clear": "Очистить",
        "Business profile": "Профиль бизнеса",
        "Owner-safe workspace settings. Only non-secret business profile fields can be edited here.": "Безопасные настройки рабочей области владельца. Здесь можно изменять только поля, не содержащие секретных данных.",
        "Profile settings": "Настройки профиля",
        "Business name": "Название бизнеса",
        "Language": "Язык бизнеса",
        "Timezone": "Часовой пояс",
        "Working hours": "Рабочее время",
        "Save profile": "Сохранить профиль",
        "Raw profile readiness": "Технический статус профиля",
        "Services": "Услуги",
        "Owner-safe service catalog. Edit services without opening admin configuration screens.": "Безопасный каталог услуг владельца. Редактируйте услуги без доступа к административным настройкам.",
        "Service setup": "Настройка услуг",
        "Add example service": "Добавить пример услуги",
        "Save services": "Сохранить услуги",
        "Services JSON": "Данные услуг",
        "Raw readiness": "Технический статус",
        "Business Memory / FAQ": "Знания бизнеса / FAQ",
        "Owner-safe receptionist facts: FAQ, policies, prices, address, and booking rules used in customer conversations.": "Безопасные знания AI-рецепциониста: FAQ, правила, цены, адрес и условия записи, используемые в диалогах с клиентами.",
        "Memory setup": "Настройка знаний",
        "Add examples": "Добавить примеры",
        "Save memory / FAQ": "Сохранить знания / FAQ",
        "Latvian": "Латышский",
        "Russian": "Русский",
        "English": "Английский",
        "Business memory LV": "Знания бизнеса LV",
        "FAQ LV": "FAQ LV",
        "Booking rules LV": "Правила записи LV",
        "Business memory RU": "Знания бизнеса RU",
        "FAQ RU": "FAQ RU",
        "Booking rules RU": "Правила записи RU",
        "Business memory EN": "Знания бизнеса EN",
        "FAQ EN": "FAQ EN",
        "Booking rules EN": "Правила записи EN",
        "Generic optional fields": "Дополнительные необязательные поля",
        "Business memory": "Знания бизнеса",
        "FAQ": "FAQ",
        "Policies": "Правила",
        "Booking rules": "Правила записи",
        "Price consistency": "Согласованность цен",
        "Service catalog is the source of truth for prices. Business Memory should explain rules and exceptions, not duplicate conflicting price lists.": "Каталог услуг является главным источником цен. Знания бизнеса должны объяснять правила и исключения, а не дублировать противоречивые прайс-листы.",
        "Edit services": "Редактировать услуги",
        "Edit memory": "Редактировать знания",
        "Raw consistency payload": "Технические данные согласованности",
        "Calendar / availability": "Календарь / доступность",
        "Owner-safe calendar status and availability settings. Google OAuth/admin setup links stay hidden from owners.": "Безопасный статус календаря и настройки доступности владельца. Ссылки Google OAuth и административные настройки скрыты.",
        "Calendar status": "Статус календаря",
        "Availability": "Доступность",
        "Save availability": "Сохранить доступность",
        "Next actions": "Следующие действия",
        "Raw calendar readiness": "Технический статус календаря",
        "Telegram channel": "Telegram-канал",
        "Owner-safe Telegram status. Bot tokens, webhook secrets and admin setup links are hidden from owners.": "Безопасный статус Telegram для владельца. Токены бота, webhook-секреты и административные ссылки скрыты.",
        "Webhook": "Webhook",
        "Usage": "Использование",
        "Raw Telegram readiness": "Технический статус Telegram",
        "Final launch checklist": "Финальная проверка запуска",
        "Owner-safe review of business profile, services, FAQ, price consistency, calendar, Telegram, billing and public launch readiness. Admin setup links and secrets are hidden.": "Безопасная проверка профиля бизнеса, услуг, FAQ, цен, календаря, Telegram, оплаты и готовности к запуску. Административные ссылки и секреты скрыты.",
        "Dashboard": "Главная",
        "Review items": "Пункты проверки",
        "Raw launch checklist": "Технические данные проверки запуска",
        "Client preview": "Предпросмотр для клиента",
        "Owner-safe dry-run preview. It uses services and Business Memory, but does not create calendar events, persist conversations, or send Telegram/SMS/WhatsApp messages.": "Безопасный тестовый предпросмотр. Он использует услуги и знания бизнеса, но не создаёт события календаря, не сохраняет диалоги и не отправляет сообщения Telegram/SMS/WhatsApp.",
        "Launch checklist": "Проверка запуска",
        "Preview chat": "Тестовый диалог",
        "Preview reply": "Тестовый ответ",
        "Catalog preview": "Предпросмотр каталога",
        "Raw preview payload": "Технические данные предпросмотра",
        "Conversation insights": "Аналитика диалогов",
        "Owner-safe read-only visibility for live interactions. Preview messages from demo mode are shown as not persisted by design.": "Безопасная аналитика реальных диалогов только для чтения. Сообщения демо-режима по умолчанию не сохраняются.",
        "What customers ask": "Что спрашивают клиенты",
        "Service interest": "Интерес к услугам",
        "Price questions": "Вопросы о ценах",
        "Answer source visibility": "Источники ответов",
        "Channel status": "Статус каналов",
        "Recent interactions": "Последние диалоги",
        "Raw owner-safe payload": "Безопасные технические данные",
        "Lead follow-up visibility": "Контроль потенциальных клиентов",
        "Owner-safe read-only queue for conversations that may need manual review. Stage 90 does not send notifications or customer messages.": "Безопасная очередь диалогов только для чтения, которым может потребоваться ручная проверка. Этот раздел не отправляет уведомления или сообщения клиентам.",
        "Insights": "Аналитика",
        "Follow-up candidates": "Кандидаты для повторного контакта",
        "Priority / reasons": "Приоритет / причины",
        "Channel visibility": "Обзор каналов",
        "Conversation states": "Состояния диалогов",
        "Recently resolved": "Недавно решённые",
        "Account center": "Центр аккаунта",
        "Owner-safe account, workspace profile and billing summary. Read-only: no payment-provider calls and no account writes.": "Безопасный обзор аккаунта, профиля рабочей области и оплаты. Только чтение: без обращений к платёжному провайдеру и изменений аккаунта.",
        "Billing": "Оплата",
        "Billing summary": "Обзор оплаты",
        "Workspace profile": "Профиль рабочей области",
        "Limitations": "Ограничения",
        "Raw account payload": "Технические данные аккаунта",
        "Setup health": "Состояние настройки",
        "Owner-safe read-only tenant data quality guard. It highlights missing setup data without changing live runtime behavior.": "Безопасная проверка качества данных только для чтения. Она показывает недостающие настройки, не меняя работу системы.",
        "Launch review": "Проверка запуска",
        "Account": "Аккаунт",
        "Components": "Компоненты",
        "Warnings": "Предупреждения",
        "Raw setup health payload": "Технические данные состояния настройки",
        "Read-only launch checkpoint": "Контрольная точка запуска только для чтения",
        "SMB launch smoke": "Проверка запуска SMB",
        "This page combines setup health, final launch review and safe client preview evidence. It never runs live dialogue, creates Calendar events or sends customer messages automatically.": "Эта страница объединяет состояние настройки, финальную проверку запуска и безопасный предпросмотр. Она не запускает реальные диалоги, не создаёт события календаря и не отправляет сообщения клиентам автоматически.",
        "Launch gates": "Проверки запуска",
        "Manual smoke checklist": "Список ручной проверки",
        "The controlled live booking/reschedule/cancel step is intentionally manual and may mutate the selected test calendar. This page does not run it.": "Контролируемый реальный тест записи, переноса и отмены намеренно выполняется вручную и может изменить выбранный тестовый календарь. Эта страница его не запускает.",
        "Owner-safe payload": "Безопасные технические данные",
        "Technical core lock": "Фиксация технического ядра",
        "Mature SMB readiness": "Готовность Mature SMB",
        "This page locks the current technical SMB product baseline. It deliberately does not claim that multilingual client navigation or the public visual website is finished; those are the next separate polish phase.": "Эта страница фиксирует текущую техническую основу SMB-продукта. Она не утверждает, что многоязычная клиентская навигация или публичный сайт уже завершены; это отдельный следующий этап.",
        "Launch smoke": "Проверка запуска",
        "Technical lock status": "Статус технической готовности",
        "Readiness gates": "Проверки готовности",
        "Next phase: client experience polish": "Следующий этап: улучшение клиентского интерфейса",
        "Owner Billing": "Оплата владельца",
        "Owner-visible read-only subscription status.": "Доступный владельцу статус подписки только для чтения.",
        "Owner dashboard": "Главная владельца",
        "Owner control center": "Центр управления владельца",
        "Owner session": "Сессия владельца",
        "Subscription settings": "Настройки подписки",
        "Plan": "Тариф",
        "Subscription status": "Статус подписки",
        "Dialogs per month override": "Лимит диалогов в месяц",
        "Trial end ISO": "Окончание пробного периода",
        "Billing provider": "Платёжный провайдер",
        "Current period end ISO": "Окончание текущего периода",
        "Customer id": "ID клиента",
        "Subscription id": "ID подписки",
        "Reset dialogs override": "Сбросить лимит диалогов",
        "Billing notes": "Примечания по оплате",
        "Save billing": "Сохранить оплату",
        "Raw": "Технические данные",
        "No data in selected window.": "За выбранный период данных нет.",
        "No interactions in selected window.": "За выбранный период диалогов нет.",
        "No customer questions detected in selected window.": "За выбранный период вопросы клиентов не найдены.",
        "No price questions detected in selected window.": "За выбранный период вопросы о ценах не найдены.",
        "No service interest detected.": "Интерес к услугам не обнаружен.",
        "No answer source metadata.": "Данные об источниках ответов отсутствуют.",
        "No channel activity.": "Активность в каналах отсутствует.",
        "No next actions": "Следующих действий нет",
        "No next actions.": "Следующих действий нет.",
        "No required actions.": "Обязательных действий нет.",
        "No components returned.": "Компоненты не найдены.",
        "No warnings returned.": "Предупреждений нет.",
        "No gates returned.": "Проверки не найдены.",
        "No checklist returned.": "Список проверки не найден.",
        "Owner login required": "Требуется вход владельца",
        "Load failed": "Не удалось загрузить",
        "Save failed": "Не удалось сохранить",
        "Saving…": "Сохранение…",
        "Unknown service": "Неизвестная услуга",
        "Source of truth": "Главный источник",
        "support controlled": "вместе с поддержкой",
        "optional attention": "рекомендуется проверка",
        "Target languages": "Целевые языки",
        "This is intentionally not marked complete by Stage 95.": "Stage 95 намеренно не отмечает этот этап как завершённый.",
    },
    "en": {},
}

_CX2_PHRASES: Dict[str, Dict[str, str]] = {
    "lv": {
        "owner UX:": "īpašnieka saskarne:",
        "settings UX:": "iestatījumu saskarne:",
        "setup complete:": "iestatīšana pabeigta:",
        "profile complete:": "profils pabeigts:",
        "runtime catalog:": "darba katalogs:",
        "active /": "aktīvi /",
        "total services": "pakalpojumi kopā",
        "missing prices:": "trūkst cenu:",
        "price consistency:": "cenu saskaņotība:",
        "total lines": "rindas kopā",
        "languages": "valodas",
        "FAQ lines": "BUJ rindas",
        "price issues": "cenu problēmas",
        "guard ready:": "pārbaude gatava:",
        "clean:": "tīrs:",
        "catalog source:": "kataloga avots:",
        "conflicts": "konflikti",
        "stale managed blocks": "novecojuši pārvaldītie bloki",
        "duplicate manual lines": "dublētas manuālās rindas",
        "orphan manual lines": "nesaistītas manuālās rindas",
        "calendar UX:": "kalendāra saskarne:",
        "availability:": "pieejamība:",
        "calendar setup:": "kalendāra iestatīšana:",
        "Google connected:": "Google savienots:",
        "calendar selected:": "kalendārs izvēlēts:",
        "not selected": "nav izvēlēts",
        "Google account:": "Google konts:",
        "Tokens and credentials are never shown here.": "Tokeni un piekļuves dati šeit nekad netiek rādīti.",
        "Telegram setup is support-controlled in this SMB phase": "Telegram iestatīšana šajā SMB posmā notiek kopā ar atbalstu",
        "Google connection/selection is support-controlled in this SMB phase": "Google savienošana un kalendāra izvēle šajā SMB posmā notiek kopā ar atbalstu",
        "Calendar is connected": "Kalendārs ir savienots",
        "Telegram metadata is ready": "Telegram dati ir gatavi",
        "runtime:": "darbība:",
        "bot token configured:": "bota tokens iestatīts:",
        "webhook secret configured:": "webhook noslēpums iestatīts:",
        "stored webhook:": "saglabātais webhook:",
        "matches recommended:": "atbilst ieteiktajam:",
        "activity seen:": "aktivitāte konstatēta:",
        "Window:": "Periods:",
        "messages:": "ziņas:",
        "Answer source:": "Atbildes avots:",
        "Reply:": "Atbilde:",
        "Tenant:": "Darba vide:",
        "Limitations:": "Ierobežojumi:",
        "Detected from": "Atrasts no",
        "status:": "statuss:",
        "preview persisted:": "priekšskatījums saglabāts:",
        "enterprise_saas_ready:": "enterprise_saas_ready:",
        "account/profile/billing UX:": "konta/profila/norēķinu saskarne:",
        "Owner email": "Īpašnieka e-pasts",
        "Display name": "Attēlojamais vārds",
        "Account status": "Konta statuss",
        "Email verified": "E-pasts apstiprināts",
        "Last login": "Pēdējā pieslēgšanās",
        "Tenant role": "Loma darba vidē",
        "Tenant binding": "Piesaiste darba videi",
        "Login code exposed": "Piekļuves kods atklāts",
        "Provider mode": "Pakalpojuma režīms",
        "Provider live": "Pakalpojums aktīvs",
        "Dialogs limit": "Dialogu limits",
        "Dialogs used": "Izmantotie dialogi",
        "Profile complete": "Profils pabeigts",
        "data_quality_clean:": "datu kvalitāte:",
        "required_setup_complete:": "obligātā iestatīšana pabeigta:",
        "launch smoke ready:": "palaišanas tests gatavs:",
        "demo tenant hardened:": "demo vide nostiprināta:",
        "QA baseline:": "QA bāze:",
        "technical core ready:": "tehniskais kodols gatavs:",
        "controlled public SaaS:": "kontrolēts publiskais SaaS:",
        "polished client launch:": "noslīpēta klienta palaišana:",
        "Expected protected regression:": "Sagaidāmā aizsargātā regresija:",
    },
    "ru": {
        "owner UX:": "интерфейс владельца:",
        "settings UX:": "интерфейс настроек:",
        "setup complete:": "настройка завершена:",
        "profile complete:": "профиль заполнен:",
        "runtime catalog:": "рабочий каталог:",
        "active /": "активных /",
        "total services": "услуг всего",
        "missing prices:": "без цены:",
        "price consistency:": "согласованность цен:",
        "total lines": "строк всего",
        "languages": "языков",
        "FAQ lines": "строк FAQ",
        "price issues": "проблем с ценами",
        "guard ready:": "проверка готова:",
        "clean:": "чисто:",
        "catalog source:": "источник каталога:",
        "conflicts": "конфликтов",
        "stale managed blocks": "устаревших управляемых блоков",
        "duplicate manual lines": "дублирующихся ручных строк",
        "orphan manual lines": "несвязанных ручных строк",
        "calendar UX:": "интерфейс календаря:",
        "availability:": "доступность:",
        "calendar setup:": "настройка календаря:",
        "Google connected:": "Google подключён:",
        "calendar selected:": "календарь выбран:",
        "not selected": "не выбран",
        "Google account:": "Аккаунт Google:",
        "Tokens and credentials are never shown here.": "Токены и данные доступа здесь никогда не отображаются.",
        "Telegram setup is support-controlled in this SMB phase": "Настройка Telegram на этом этапе SMB выполняется вместе с поддержкой",
        "Google connection/selection is support-controlled in this SMB phase": "Подключение Google и выбор календаря на этом этапе SMB выполняются вместе с поддержкой",
        "Calendar is connected": "Календарь подключён",
        "Telegram metadata is ready": "Данные Telegram готовы",
        "runtime:": "работа:",
        "bot token configured:": "токен бота настроен:",
        "webhook secret configured:": "webhook-секрет настроен:",
        "stored webhook:": "сохранённый webhook:",
        "matches recommended:": "соответствует рекомендуемому:",
        "activity seen:": "активность обнаружена:",
        "Window:": "Период:",
        "messages:": "сообщений:",
        "Answer source:": "Источник ответа:",
        "Reply:": "Ответ:",
        "Tenant:": "Рабочая область:",
        "Limitations:": "Ограничения:",
        "Detected from": "Определено из",
        "status:": "статус:",
        "preview persisted:": "предпросмотр сохранён:",
        "enterprise_saas_ready:": "enterprise_saas_ready:",
        "account/profile/billing UX:": "интерфейс аккаунта, профиля и оплаты:",
        "Owner email": "Email владельца",
        "Display name": "Отображаемое имя",
        "Account status": "Статус аккаунта",
        "Email verified": "Email подтверждён",
        "Last login": "Последний вход",
        "Tenant role": "Роль в рабочей области",
        "Tenant binding": "Привязка к рабочей области",
        "Login code exposed": "Код входа раскрыт",
        "Provider mode": "Режим провайдера",
        "Provider live": "Провайдер активен",
        "Dialogs limit": "Лимит диалогов",
        "Dialogs used": "Использовано диалогов",
        "Profile complete": "Профиль заполнен",
        "data_quality_clean:": "качество данных:",
        "required_setup_complete:": "обязательная настройка завершена:",
        "launch smoke ready:": "проверка запуска готова:",
        "demo tenant hardened:": "демо-среда защищена:",
        "QA baseline:": "базовая QA-проверка:",
        "technical core ready:": "техническое ядро готово:",
        "controlled public SaaS:": "контролируемый публичный SaaS:",
        "polished client launch:": "полированный клиентский запуск:",
        "Expected protected regression:": "Ожидаемая защищённая регрессия:",
    },
    "en": {},
}

_TECHNICAL_HEADINGS = {
    "Raw", "Raw readiness", "Raw profile readiness", "Raw consistency payload",
    "Raw calendar readiness", "Raw Telegram readiness", "Raw launch checklist",
    "Raw preview payload", "Raw owner-safe payload", "Raw account payload",
    "Raw setup health payload", "Owner-safe payload",
}

_NAV_DUPLICATE_LABELS = {
    "Workspace", "Setup", "Logout", "Owner dashboard", "Account center",
    "Owner control center", "Owner session", "Dashboard", "Account",
}


def cx2_exact_translations(lang: str) -> Dict[str, str]:
    normalized = str(lang or "en").strip().lower()
    result = dict(_CX2_EXACT.get(normalized, {}))
    result.update(ui_known_labels(normalized))
    return result


def cx2_phrase_translations(lang: str) -> Dict[str, str]:
    return dict(_CX2_PHRASES.get(str(lang or "en").strip().lower(), {}))


def _translate_visible_html(fragment: str, translations: Mapping[str, str]) -> str:
    if not translations:
        return fragment

    def replace_text(match: re.Match[str]) -> str:
        raw = match.group(1)
        stripped = html.unescape(raw.strip())
        translated = translations.get(stripped)
        if translated is None:
            return match.group(0)
        leading = raw[: len(raw) - len(raw.lstrip())]
        trailing = raw[len(raw.rstrip()):]
        return ">" + leading + html.escape(translated, quote=False) + trailing + "<"

    output = re.sub(r">([^<>]+)<", replace_text, fragment)
    for attr in ("placeholder", "title", "aria-label"):
        pattern = re.compile(rf'({attr}\s*=\s*["\'])(.*?)(["\'])', re.I | re.S)
        output = pattern.sub(
            lambda m: m.group(1) + html.escape(translations.get(html.unescape(m.group(2)), html.unescape(m.group(2))), quote=True) + m.group(3),
            output,
        )
    return output


def _extract_legacy_parts(legacy_html: str) -> tuple[str, str, list[str]]:
    source = str(legacy_html or "")
    styles = "\n".join(re.findall(r"<style[^>]*>(.*?)</style>", source, flags=re.I | re.S))
    body_match = re.search(r"<body[^>]*>(.*?)</body>", source, flags=re.I | re.S)
    body = body_match.group(1) if body_match else source
    scripts = re.findall(r"<script[^>]*>(.*?)</script>", body, flags=re.I | re.S)
    body = re.sub(r"<script[^>]*>.*?</script>", "", body, flags=re.I | re.S)
    return styles, body, scripts


def _adapter_script(lang: str, exact: Mapping[str, str], phrases: Mapping[str, str]) -> str:
    technical = {key: exact.get(key, key) for key in _TECHNICAL_HEADINGS}
    nav_duplicates = list(_NAV_DUPLICATE_LABELS)
    return r'''
(function(){
  const exact=__EXACT__;const phrases=__PHRASES__;const technical=__TECHNICAL__;const navDuplicates=new Set(__NAV_DUPLICATES__);
  const technicalSummary=__TECHNICAL_SUMMARY__;
  function translateValue(value){const raw=String(value??'');const trimmed=raw.trim();if(!trimmed)return raw;if(Object.prototype.hasOwnProperty.call(exact,trimmed)){return raw.replace(trimmed,exact[trimmed]);}let out=raw;Object.keys(phrases).sort((a,b)=>b.length-a.length).forEach(k=>{if(out.includes(k))out=out.split(k).join(phrases[k]);});return out;}
  function translateNode(node){if(node.nodeType===Node.TEXT_NODE){const next=translateValue(node.nodeValue);if(next!==node.nodeValue)node.nodeValue=next;return;}if(node.nodeType!==Node.ELEMENT_NODE)return;['placeholder','title','aria-label'].forEach(a=>{if(node.hasAttribute&&node.hasAttribute(a)){const old=node.getAttribute(a);const next=translateValue(old);if(next!==old)node.setAttribute(a,next);}});}
  function translateTree(root){const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT|NodeFilter.SHOW_ELEMENT);let n=root;while(n){translateNode(n);n=walker.nextNode();}}
  function hideDuplicateNav(){document.querySelectorAll('.rq-legacy-main a,.rq-legacy-main button').forEach(el=>{const label=(el.textContent||'').trim();const onclick=el.getAttribute('onclick')||'';const href=el.getAttribute('href')||'';if(navDuplicates.has(label)||/\/owner\/(workspace|setup|dashboard|account|logout)(?:\/ui)?/.test(onclick+' '+href)){if(!/load|refresh|save/i.test(label))el.classList.add('rq-cx2-hidden-nav');}});}
  function convertTechnicalCards(){document.querySelectorAll('.rq-legacy-main h1,.rq-legacy-main h2,.rq-legacy-main h3').forEach(h=>{const original=(h.textContent||'').trim();if(!Object.prototype.hasOwnProperty.call(technical,original)&&!Object.values(technical).includes(original))return;const card=h.closest('.card,.rq-card')||h.parentElement;if(!card||card.tagName==='DETAILS'||card.dataset.rqTechnical==='1')return;const details=document.createElement('details');details.className='rq-details rq-cx2-technical';details.dataset.rqTechnical='1';const summary=document.createElement('summary');summary.textContent=technicalSummary;details.appendChild(summary);Array.from(card.childNodes).forEach(child=>{if(child!==h)details.appendChild(child);});card.replaceWith(details);});}
  function polish(){translateTree(document.querySelector('.rq-legacy-main')||document.body);hideDuplicateNav();convertTechnicalCards();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',polish);else polish();
  const target=document.querySelector('.rq-legacy-main');if(target){new MutationObserver(mutations=>{mutations.forEach(m=>{m.addedNodes.forEach(n=>{translateTree(n);});});hideDuplicateNav();convertTechnicalCards();}).observe(target,{childList:true,subtree:true});}
})();
'''.replace("__EXACT__", json.dumps(dict(exact), ensure_ascii=False))\
   .replace("__PHRASES__", json.dumps(dict(phrases), ensure_ascii=False))\
   .replace("__TECHNICAL__", json.dumps(technical, ensure_ascii=False))\
   .replace("__NAV_DUPLICATES__", json.dumps(nav_duplicates, ensure_ascii=False))\
   .replace("__TECHNICAL_SUMMARY__", json.dumps(exact.get("Technical details", {"lv":"Tehniskā informācija","ru":"Технические данные"}.get(lang,"Technical details")), ensure_ascii=False))


def render_migrated_owner_page(
    *,
    legacy_html: str,
    title: str,
    lang: str,
    tenant_id: str,
    active_nav: str,
    page_key: str,
) -> str:
    styles, body, scripts = _extract_legacy_parts(legacy_html)
    exact = cx2_exact_translations(lang)
    phrases = cx2_phrase_translations(lang)
    translated_body = _translate_visible_html(body, exact)
    content = f'<section class="rq-legacy-main rq-cx2-page" data-rq-page="{html.escape(page_key, quote=True)}">{translated_body}</section>'
    legacy_style = f"<style>{styles}</style>" if styles.strip() else ""
    inline_script = "\n".join(scripts) + "\n" + _adapter_script(lang, exact, phrases)
    localized_title = exact.get(title, title)
    return render_repliq_shell(
        title=localized_title,
        lang=lang,
        tenant_id=tenant_id,
        content_html=content,
        active_nav=active_nav,
        inline_script=inline_script,
        extra_head_before_css=legacy_style,
        body_data={"rq-cx-phase": CX2_MIGRATION_VERSION, "rq-cx-page": page_key},
    )


def cx2_translation_counts() -> Dict[str, int]:
    return {lang: len(_CX2_EXACT.get(lang, {})) for lang in ("lv", "ru", "en")}
